// Phrase tables. Everything here is matched in code, never by the model.
// A phrase belongs to exactly one category. `suggestion` is printed under the
// carets; an empty string means "delete it". `pattern` overrides the default
// word-boundary regex for phrases that need punctuation-aware matching.

import type { Category } from "./types";

export interface PhraseEntry {
  phrase: string;
  category: Category;
  suggestion?: string;
  /** Year the phrase was deprecated. Only for the deprecated category. */
  since?: number;
  /** Regex source; compiled with the flags "giu" (plus "m" when it anchors). */
  pattern?: string;
}

type Maker = (phrase: string, suggestion?: string, pattern?: string) => PhraseEntry;

const maker =
  (category: Category): Maker =>
  (phrase, suggestion, pattern) => ({ phrase, category, suggestion, pattern });

const c = maker("corporate");
const pa = maker("passive_aggressive");
const u = maker("urgency");
const li = maker("linkedin");
const ac = maker("academic");
const rd = maker("reddit");
const po = maker("politician");
const te = maker("teenager");
const ai = maker("ai_slop");
const fi = maker("filler");
const he = maker("hedge");
const dep = (phrase: string, since: number, suggestion?: string, pattern?: string): PhraseEntry => ({
  phrase,
  category: "deprecated",
  since,
  suggestion,
  pattern,
});

const NW = "(?<![\\p{L}\\p{N}_])";
const NWA = "(?![\\p{L}\\p{N}_])";

export const LEXICON: readonly PhraseEntry[] = [
  // corporate
  c("circle back", "follow up"),
  c("circling back", "following up"),
  c("synergy", "cooperation"),
  c("synergies", "cooperation"),
  c("leverage", "use"),
  c("touch base", "talk"),
  c("move the needle", "make a difference"),
  c("low-hanging fruit", "easy wins"),
  c("low hanging fruit", "easy wins"),
  c("bandwidth", "time"),
  c("going forward", "from now on"),
  c("moving forward", "from now on"),
  c("at the end of the day", ""),
  c("double-click on", "look at"),
  c("double click on", "look at"),
  c("boil the ocean", "do too much"),
  c("take this offline", "discuss later"),
  c("deep dive", "look"),
  c("alignment", "agreement"),
  c("align on", "agree on"),
  c("value-add", "benefit"),
  c("core competency", "strength"),
  c("best practice", "what works"),
  c("best practices", "what works"),
  c("paradigm", "model"),
  c("drill down", "look closer"),
  c("action item", "task"),
  c("action items", "tasks"),
  c("deliverable", "result"),
  c("deliverables", "results"),
  c("stakeholder", "person involved"),
  c("stakeholders", "people involved"),
  c("loop in", "include"),
  c("loop you in", "include you"),
  c("in the loop", "informed"),
  c("quick sync", "short call"),
  c("run it up the flagpole", "ask"),
  c("north star", "goal"),
  c("table stakes", "the minimum"),
  c("thought leader", "expert"),
  c("thought leadership", "expertise"),
  c("ecosystem", "market"),
  c("holistic", "whole"),
  c("streamline", "simplify"),
  c("scalable", "able to grow"),
  c("unlock value", "be useful"),
  c("empower", "let"),
  c("ideate", "think"),
  c("learnings", "lessons"),
  c("the ask", "the request"),
  c("cadence", "schedule"),
  c("key takeaways", "main points"),
  c("socialize this", "share this"),
  c("bake in", "include"),
  c("granular", "detailed"),
  c("optics", "appearance"),
  c("pivot", "change direction"),
  c("disrupt", "change"),
  c("reach out", "contact"),
  c("touch points", "contacts"),
  c("on my radar", "known to me"),
  c("ping me", "message me"),
  c("parking lot", "later"),
  c("win-win", "good for both"),
  c("game plan", "plan"),
  c("hit the ground running", "start quickly"),
  c("think outside the box", "think differently"),
  c("at scale", "widely"),
  c("on the same page", "in agreement"),
  c("bring to the table", "offer"),
  c("best-in-class", "good"),
  c("world-class", "good"),
  c("cutting-edge", "new"),
  c("mission-critical", "important"),
  c("value proposition", "offer"),
  c("customer-centric", "for customers"),
  c("level set", "agree on the basics"),
  c("per se", ""),
  c("net-net", "overall"),

  // passive aggressive
  pa("per my last email", "as I wrote earlier"),
  pa("per my previous email", "as I wrote earlier"),
  pa("as previously stated", "as I said"),
  pa("as previously mentioned", "as I said"),
  pa("as I mentioned", ""),
  pa("as discussed", ""),
  pa("just to clarify", "to clarify"),
  pa("just a gentle reminder", "reminder"),
  pa("gentle reminder", "reminder"),
  pa("friendly reminder", "reminder"),
  pa("not sure if you saw", ""),
  pa("not sure if you got my", ""),
  pa("correct me if I'm wrong", ""),
  pa("with all due respect", ""),
  pa("no offense but", ""),
  pa("no offence but", ""),
  pa("thanks in advance", "thank you"),
  pa("going forward please", "please"),
  pa("I'll let you decide", "you decide"),
  pa("as you know", ""),
  pa("obviously", ""),
  pa("clearly", ""),
  pa("kindly", "please"),
  pa("please advise", "what should I do?"),
  pa("for future reference", "next time"),
  pa("noted.", "", "^[ \\t]*noted\\.?[ \\t]*$"),
  pa("as per", "per"),
  pa("I'm sure you're busy but", ""),
  pa("if it's not too much trouble", ""),
  pa("whenever you get a chance", "by <date>"),
  pa("any update on this", "what is the status"),
  pa("bumping this", ""),
  pa("following up on my", "following up"),
  pa("I hate to be that person", ""),
  pa("respectfully", ""),
  pa("agree to disagree", ""),
  pa("I thought I was clear", ""),
  pa("as stated in the subject line", ""),

  // urgency
  u("ASAP", "by <date>"),
  u("urgent", "<state the deadline>"),
  u("urgently", "by <date>"),
  u("as soon as possible", "by <date>"),
  u("EOD", "by 17:00"),
  u("by end of day", "by 17:00"),
  u("end of day today", "17:00 today"),
  u("immediately", "now"),
  u("time-sensitive", "due <date>"),
  u("right away", "now"),
  u("without delay", "now"),
  u("top priority", "first"),
  u("drop everything", ""),
  u("act now", ""),
  u("last chance", ""),
  u("don't miss out", ""),
  u("final notice", ""),
  u("critical", "important"),

  // linkedin
  li("thrilled to announce", "announcing"),
  li("excited to announce", "announcing"),
  li("excited to share", "sharing"),
  li("proud to share", "sharing"),
  li("humbled", "proud"),
  li("honored to", "glad to"),
  li("honoured to", "glad to"),
  li("agree?", "", `${NW}agree\\?`),
  li("thoughts?", "", `${NW}thoughts\\?`),
  li("let that sink in", ""),
  li("game-changer", "improvement"),
  li("game changer", "improvement"),
  li("hustle", "work"),
  li("the grind", "work"),
  li("#blessed", "", "#blessed\\b"),
  li("journey", ""),
  li("growth mindset", "willingness to learn"),
  li("10x", "ten times"),
  li("rockstar", "good"),
  li("ninja", "good"),
  li("guru", "expert"),
  li("personal brand", "reputation"),
  li("I'm not going to lie", ""),
  li("lessons I learned", "what I learned"),
  li("story time", ""),
  li("let me explain", ""),
  li("here's what I learned", "what I learned"),
  li("here's why", ""),
  li("here's the thing", ""),
  li("from the trenches", "at work"),
  li("I'll go first", ""),
  li("big news", "news"),
  li("new chapter", "new job"),
  li("servant leader", "manager"),
  li("crushing it", "doing well"),
  li("level up", "improve"),
  li("side hustle", "second job"),
  li("the algorithm", ""),
  li("repost if", ""),
  li("comment below", ""),
  li("follow me for more", ""),
  li("I don't usually post", ""),
  li("grateful for this opportunity", "glad"),
  li("dream job", "job"),

  // academic
  ac("it is well known", "<cite it>"),
  ac("it is widely accepted", "<cite it>"),
  ac("trivially", "<show it>"),
  ac("it is obvious that", "<show it>"),
  ac("beyond the scope", "<address it>"),
  ac("outside the scope", "<address it>"),
  ac("left as an exercise", "<do it>"),
  ac("novel", "new"),
  ac("to the best of our knowledge", ""),
  ac("to our knowledge", ""),
  ac("we argue that", "we claim"),
  ac("it can be shown", "<show it>"),
  ac("without loss of generality", ""),
  ac("seminal", "early"),
  ac("in this paper we", "we"),
  ac("future work", "<do it>"),
  ac("promising", "<report numbers>"),
  ac("nontrivial", "hard"),
  ac("non-trivial", "hard"),
  ac("the literature", "prior work"),
  ac("a growing body of", "several"),
  ac("it should be noted that", ""),
  ac("interestingly", ""),
  ac("rigorous", ""),
  ac("extensive experiments", "experiments"),
  ac("state-of-the-art", "best known"),
  ac("outperforms", "beats"),
  ac("we believe", ""),
  ac("it is easy to see", "<show it>"),
  ac("the reader may verify", "<verify it>"),

  // reddit
  rd("this.", "", "^[ \\t]*this\\.[ \\t]*$"),
  rd("EDIT:", "", "^[ \\t]*edit[ \\t]*[:\\-]"),
  rd("thanks for the gold", ""),
  rd(
    "as a ...,",
    "",
    `${NW}as an? (?!result\\b|matter\\b|consequence\\b|whole\\b|rule\\b|reminder\\b|side\\b|note\\b|way\\b|first\\b|last\\b|final\\b|general\\b|reference\\b|precaution\\b|courtesy\\b|favor\\b|favour\\b)[\\p{L}]+(?:[ \\-][\\p{L}]+)?,`,
  ),
  rd("source?", "", `${NW}source\\?`),
  rd("downvoted", ""),
  rd("downvote", ""),
  rd("upvote", ""),
  rd("upvotes", ""),
  rd("OP", "the author", `${NW}OP${NWA}`),
  rd("TIL", "I learned"),
  rd("ELI5", "explain simply"),
  rd("IANAL", "I am not a lawyer"),
  rd("AMA", ""),
  rd("well, actually", "actually", `${NW}well,? actually${NWA}`),
  rd("unpopular opinion", "opinion"),
  rd("am I the only one", ""),
  rd("this needs more upvotes", ""),
  rd("came here to say this", ""),
  rd("underrated comment", ""),
  rd("sir, this is a", ""),
  rd("ftfy", "fixed"),
  rd("/s", "", `(?<=\\s|^)/s${NWA}`),
  rd("r/", "", "(?<![\\p{L}\\p{N}_/])r/[A-Za-z0-9_]+"),
  rd("u/", "", "(?<![\\p{L}\\p{N}_/])u/[A-Za-z0-9_]+"),
  rd("citation needed", ""),
  rd("obligatory", ""),
  rd("username checks out", ""),
  rd("reddit moment", ""),
  rd("sort by controversial", ""),
  rd("narrator:", "", `${NW}narrator:`),
  rd("press x to doubt", ""),
  rd("this is the way", ""),
  rd("take my upvote", ""),
  rd("touch grass", "go outside"),
  rd("found the", "", `${NW}found the [\\p{L}]+(?=[ \\t]*$|[.!])`),
  rd("in before", ""),
  rd("inb4", ""),

  // politician
  po("let me be clear", ""),
  po("let me be very clear", ""),
  po("hard-working families", "people"),
  po("hardworking families", "people"),
  po("the American people", "people"),
  po("the people of this country", "people"),
  po("at this time", "now"),
  po("make no mistake", ""),
  po("I have always said", ""),
  po("look,", "", "^[ \\t]*look,"),
  po("the fact of the matter is", ""),
  po("on both sides", ""),
  po("I take full responsibility", "<say what changes>"),
  po("mistakes were made", "I made a mistake"),
  po("monitoring the situation", "doing nothing"),
  po("thoughts and prayers", ""),
  po("unprecedented", "new"),
  po("in these uncertain times", "now"),
  po("my fellow", ""),
  po("our great", "our"),
  po("common-sense", ""),
  po("common sense solutions", "solutions"),
  po("fake news", "<say what is false>"),
  po("radical", "<say what they propose>"),
  po("the elites", "<name them>"),
  po("the establishment", "<name them>"),
  po("real change", "change"),
  po("I hear you", ""),
  po("what I will say is", ""),
  po("that's a great question", "<answer it>"),
  po("I'm glad you asked", "<answer it>"),
  po("we are where we are", ""),
  po("lessons will be learned", "<say which>"),
  po("the silent majority", "<name them>"),
  po("for the record", ""),
  po("I won't dignify that", ""),
  po("at the appropriate time", "<say when>"),
  po("in due course", "<say when>"),
  po("all options are on the table", "<say which>"),
  po("no comment", ""),

  // teenager
  te("no cap", "really"),
  te("fr fr", "really"),
  te("fr", "really"),
  te("lowkey", "slightly"),
  te("highkey", "very"),
  te("it's giving", "it seems"),
  te("slay", ""),
  te("rizz", "charm"),
  te("bet", "ok", "^[ \\t]*bet[.!]?[ \\t]*$"),
  te("cringe", "embarrassing"),
  te("sus", "suspicious"),
  te("bussin", "good"),
  te("mid", "average", `${NW}mid(?=[.!?,]|[ \\t]*$)`),
  te("based", "", `${NW}based(?=[.!?,]|[ \\t]*$)`),
  te("delulu", "deluded"),
  te("ick", ""),
  te("skibidi", ""),
  te("sigma", ""),
  te("gyat", ""),
  te("cooked", "done for"),
  te("I'm dead", "that's funny"),
  te("tbh", "honestly"),
  te("ngl", "honestly"),
  te("idk", "I don't know"),
  te("smh", ""),
  te("iykyk", ""),
  te("vibe", "feeling"),
  te("vibes", "feelings"),
  te("goated", "excellent"),
  te("W", "win", "(?<![\\p{L}\\p{N}_.])W(?![\\p{L}\\p{N}_.])"),
  te("take the L", "accept the loss"),
  te("yeet", "throw"),
  te("salty", "bitter"),
  te("ghosted", "ignored"),
  te("stan", "fan", `${NW}stan${NWA}`),
  te("simp", ""),
  te("glow up", "improvement"),
  te("main character", ""),
  te("era", "phase", `${NW}(?:my|her|his|their) [\\p{L}]+ era${NWA}`),
  te("period.", "", "^[ \\t]*periodt?\\.?[ \\t]*$"),
  te("slaps", "is good"),
  te("hits different", "is different"),
  te("understood the assignment", "did it right"),
  te("rent free", ""),
  te("unalive", "kill"),
  te("boomer", "older person"),
  te("sending me", "making me laugh"),
  te("not me", "", "^[ \\t]*not me [\\p{L}]+"),
  te("bruh", ""),
  te("sheesh", ""),
  te("lit", "", `${NW}lit(?=[.!?,]|[ \\t]*$)`),

  // ai slop
  ai("delve", "look"),
  ai("delves", "looks"),
  ai("delving", "looking"),
  ai("tapestry", ""),
  ai("in today's fast-paced world", "today"),
  ai("it's important to note", ""),
  ai("it is important to note", ""),
  ai("it's worth noting", ""),
  ai("it is worth noting", ""),
  ai("as an AI", ""),
  ai("I hope this helps", ""),
  ai("certainly!", "", `${NW}certainly!`),
  ai("great question", ""),
  ai("navigate the complexities", "handle"),
  ai("multifaceted", "complex"),
  ai("ever-evolving", "changing"),
  ai("testament to", "shows"),
  ai("unlock the potential", "enable"),
  ai("elevate", "improve"),
  ai("embark on a journey", "start"),
  ai("in the realm of", "in"),
  ai("it is crucial", ""),
  ai("a myriad of", "many"),
  ai("game-changing", "new"),
  ai("seamless", "smooth"),
  ai("seamlessly", "smoothly"),
  ai("harness", "use"),
  ai("foster", "encourage"),
  ai("robust", "strong"),
  ai("landscape", "field"),
  ai("dive into", "look at"),
  ai("let's dive in", ""),
  ai("whether you're a", "", `${NW}whether you['’]?re an? [\\p{L}]+ or an? [\\p{L}]+`),
  ai("at its core", ""),
  ai("ultimately,", "", "^[ \\t]*ultimately,"),
  ai("furthermore", "also"),
  ai("moreover", "also"),
  ai("additionally", "also"),
  ai("comprehensive", "full"),
  ai("meticulous", "careful"),
  ai("pivotal", "key"),
  ai("underscores", "shows"),
  ai("vibrant", "lively"),
  ai("I'd be happy to", ""),
  ai("rest assured", ""),
  ai("it's not just about", "", `${NW}it['’]?s not (?:just|only) about`),
  ai("in the ever-changing", "in the changing"),
  ai("crucial role", "role"),
  ai("plays a vital role", "matters"),

  // filler
  fi("I hope this email finds you well", ""),
  fi("I hope this finds you well", ""),
  fi("I hope you're doing well", ""),
  fi("I hope you are doing well", ""),
  fi("hope all is well", ""),
  fi("just checking in", "checking in"),
  fi("just wanted to", "wanted to"),
  fi("I just wanted to reach out", ""),
  fi("quick question", "question"),
  fi("no worries if not", ""),
  fi("as the title says", ""),
  fi("in other words", ""),
  fi("needless to say", ""),
  fi("it goes without saying", ""),
  fi("at this point in time", "now"),
  fi("in order to", "to"),
  fi("due to the fact that", "because"),
  fi("the fact that", "that"),
  fi("basically", ""),
  fi("actually", ""),
  fi("essentially", ""),
  fi("very", ""),
  fi("really", ""),
  fi("literally", ""),
  fi("in my humble opinion", "I think"),
  fi("IMHO", "I think"),
  fi("for what it's worth", ""),
  fi("to be honest", ""),
  fi("honestly", ""),
  fi("sorry for the long message", ""),
  fi("please find attached", "attached is"),
  fi("attached please find", "attached is"),
  fi("for your information", ""),
  fi("with that being said", ""),
  fi("that being said", ""),
  fi("at the present moment", "now"),
  fi("each and every", "every"),

  // hedge
  he("kind of", ""),
  he("sort of", ""),
  he("maybe", ""),
  he("perhaps", ""),
  he("I think", ""),
  he("I feel like", ""),
  he("possibly", ""),
  he("could potentially", "could"),
  he("potentially", ""),
  he("somewhat", ""),
  he("a bit", ""),
  he("to some extent", ""),
  he("arguably", ""),
  he("it seems like", ""),
  he("it seems", ""),
  he("apparently", ""),
  he("I guess", ""),
  he("not sure but", ""),
  he("I'm not sure but", ""),
  he("I'm no expert but", ""),
  he("in a sense", ""),
  he("more or less", ""),
  he("if that makes sense", ""),
  he("does that make sense?", ""),
  he("I could be wrong but", ""),
  he("just my two cents", ""),
  he("I might be wrong", ""),
  he("or something", ""),
  he("I suppose", ""),

  // deprecated
  dep("new normal", 2021, "now"),
  dep("unprecedented times", 2021, "now"),
  dep("pivot to digital", 2021, ""),
  dep("web 2.0", 2010, "the web"),
  dep("metaverse", 2023, ""),
  dep("the great resignation", 2022, ""),
  dep("quiet quitting", 2023, "working to contract"),
  dep("growth hacking", 2018, "marketing"),
  dep("big data", 2016, "data"),
  dep("rockstar developer", 2014, "developer"),
  dep("web3", 2023, ""),
  dep("NFT", 2023, "", `${NW}NFTs?${NWA}`),
  dep("hustle culture", 2021, "overwork"),
  dep("IoT", 2018, "connected devices", `${NW}IoT${NWA}`),
  dep("gamification", 2015, ""),
  dep("digital transformation", 2022, ""),
  dep("blockchain", 2019, "a database"),
  dep("work hard, play hard", 2015, ""),
  dep("girlboss", 2021, ""),
  dep("in these trying times", 2021, "now"),
  dep("social distancing", 2022, ""),
  dep("zoom fatigue", 2022, "tiredness"),
  dep("AI-powered", 2024, "<say what it does>"),
  dep("prompt engineering", 2025, "writing"),
  dep("cloud-native", 2020, ""),
  dep("agile transformation", 2019, ""),
  dep("millennials", 2019, "people in their thirties"),
];

/** Words counted for the repetition rule even when they are not in a phrase entry. */
export const TRACKED_WORDS: readonly string[] = [
  "alignment",
  "synergy",
  "leverage",
  "impact",
  "robust",
  "delve",
  "journey",
];

/** Openers that mark a paragraph as a conclusion. Everything after it is unreachable. */
export const TERMINATORS: readonly string[] = [
  "tl;dr",
  "tldr",
  "in conclusion",
  "to conclude",
  "in summary",
  "to summarize",
  "to summarise",
  "long story short",
  "bottom line",
  "net net",
  "to sum up",
  "in closing",
];

/** All-caps tokens that are ordinary words or acronyms everyone knows. */
export const ACRONYM_ALLOWLIST: ReadonlySet<string> = new Set([
  "OK", "AM", "PM", "US", "UK", "EU", "USA", "ID", "TV", "PDF", "URL", "HTML", "CSS", "FAQ",
  "CEO", "CTO", "CFO", "COO", "CIO", "HR", "IT", "PR", "PS", "TL", "DR", "FYI", "ASAP", "EOD",
  "EOW", "COB", "RSVP", "DIY", "AI", "ML", "API", "IMO", "IMHO", "TBH", "NGL", "IDK", "SMH",
  "LOL", "OMG", "WTF", "BTW", "TLDR", "EDIT", "NB", "RE", "FW", "CC", "BCC", "USD", "EUR",
  "GBP", "GDP", "NASA", "FBI", "CIA", "UN", "NATO", "ETA", "VS", "IYKYK", "OP", "TIL", "IANAL",
  "AMA", "NFT", "NFTS", "PLEASE", "URGENT", "IMPORTANT", "NOW", "TODAY", "STOP", "READ",
  "ACTION", "REQUIRED", "NOTE", "WARNING", "ATTENTION", "FINAL", "REMINDER", "HELP", "THANKS",
  "THANK", "YOU", "ALL", "THE", "THIS", "NOT", "AND", "FOR", "ARE", "YES", "NO", "DO", "SO",
  "TO", "IS", "IN", "ON", "OF", "AT", "BY", "OR", "IF", "AS", "WE", "BE", "MY", "ME", "HI",
  "NEW", "BIG", "WIN", "DEAL", "SALE", "FREE", "LIVE", "OUT", "OFF", "GO", "UP", "GET", "BUY",
  "DONE", "SENT", "DUE", "ASK", "END", "DAY", "ONE", "TWO", "TEN", "PC", "MAC", "IOS", "APP",
  "SEO", "CV", "MD", "PHD", "MBA", "BA", "BS", "MS", "JS", "TS", "CPU", "GPU", "RAM",
  "SSD", "USB", "WIFI", "GPS", "SMS", "DM", "DMS", "OKAY", "LMAO", "ROFL", "IRL", "AFAIK",
  "FOMO", "YOLO", "COVID", "NSFW", "ELI", "AMEN", "BRB", "TTYL", "ICYMI", "RIP", "MVP",
]);
